# Generated by Django 2.2.2 on 2019-07-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='brand',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='codename',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cores',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.RemoveField(
            model_name='cpus',
            name='feature',
        ),
        migrations.AddField(
            model_name='cpus',
            name='feature',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='foundry',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='generation',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='integrated_graphics',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='market',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='memory_support',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier_unlocked',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='process_size',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='production_status',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='socket',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='tdp',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='threads',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
