# Generated by Django 2.2.2 on 2019-07-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0003_auto_20190713_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
