# Generated by Django 2.2.2 on 2019-07-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0004_auto_20190714_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Brand'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='codename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.CodeName'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Core'),
        ),
        migrations.RemoveField(
            model_name='cpus',
            name='feature',
        ),
        migrations.AddField(
            model_name='cpus',
            name='feature',
            field=models.ManyToManyField(to='cpudb.Feature'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='foundry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foundry_cpus', to='cpudb.Foundry'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Generation'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='integrated_graphics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.IntegratedGraphics'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Market'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='memory_support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Memory'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Multiplier'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier_unlocked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.MultiplierUnlocked'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Package'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='process_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_size_cpus', to='cpudb.ProcessSize'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='production_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.ProductionStatus'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='socket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socket_cpus', to='cpudb.Socket'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='tdp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.TDP'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='threads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Thread'),
        ),
    ]
