# Generated by Django 2.2.2 on 2019-06-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0004_cpu_url_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpus',
            name='brand_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Brand'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='codename_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.CodeName'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='cores_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Core'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='feature_f',
            field=models.ManyToManyField(to='cpudb.Feature'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='foundry_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foundry_cpus', to='cpudb.Foundry'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='generation_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Generation'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='integrated_graphics_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.IntegratedGraphics'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='market_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Market'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='memory_support_f',
            field=models.ManyToManyField(to='cpudb.Memory'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='multiplier_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Multiplier'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='multiplier_unlocked_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.MultiplierUnlocked'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='package_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Pageage'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='process_size_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_size_cpus', to='cpudb.ProcessSize'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='production_status_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.ProductionStatus'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='socket_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socket_cpus', to='cpudb.Socket'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='t_case_max_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.TCaseMax'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='tdp_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.TDP'),
        ),
        migrations.AddField(
            model_name='cpus',
            name='threads_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Thread'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='base_clock',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='brand',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l1',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l2',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l3',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l4',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='codename',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cores',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='die_size',
            field=models.CharField(max_length=32),
        ),
        migrations.RemoveField(
            model_name='cpus',
            name='feature',
        ),
        migrations.AddField(
            model_name='cpus',
            name='feature',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='foundry',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='frequency',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='generation',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='integrated_graphics',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='market',
            field=models.CharField(max_length=32),
        ),
        migrations.RemoveField(
            model_name='cpus',
            name='memory_support',
        ),
        migrations.AddField(
            model_name='cpus',
            name='memory_support',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier_unlocked',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='part',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='process_size',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='production_status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='released',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='smp_cpus',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='socket',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='t_case_max',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='tdp',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='threads',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='transistors',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='turbo_clock',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='voltage',
            field=models.CharField(max_length=32),
        ),
    ]
