# Generated by Django 2.2.2 on 2019-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0005_auto_20190629_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='brand',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l3',
            field=models.CharField(default=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l4',
            field=models.CharField(default=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='foundry',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
