# Generated by Django 2.2.2 on 2019-07-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0005_auto_20190714_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cores',
        ),
        migrations.RenameField(
            model_name='cpus',
            old_name='cores',
            new_name='core',
        ),
        migrations.RenameField(
            model_name='cpus',
            old_name='threads',
            new_name='thread',
        ),
        migrations.AlterField(
            model_name='cpus',
            name='brand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Brand'),
        ),
    ]
