# Generated by Django 2.2.2 on 2019-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0006_auto_20190629_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='base_clock',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l1',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l2',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l3',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cache_l4',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='codename',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='cores',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='die_size',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='feature',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='foundry',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='frequency',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='generation',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='integrated_graphics',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='market',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='memory_support',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='multiplier_unlocked',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='part',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='process_size',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='production_status',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='released',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='smp_cpus',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='socket',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='t_case_max',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='tdp',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='threads',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='transistors',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='turbo_clock',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='voltage',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
