# Generated by Django 2.2.2 on 2019-07-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0006_auto_20190714_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpus',
            old_name='frequency',
            new_name='afrequency',
        ),
    ]
