# Generated by Django 2.2.2 on 2019-06-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0007_auto_20190629_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
