# Generated by Django 2.2.2 on 2019-07-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0007_auto_20190714_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpus',
            old_name='afrequency',
            new_name='frequency',
        ),
    ]
