# Generated by Django 2.2.2 on 2019-06-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0008_auto_20190629_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='part',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
