# Generated by Django 2.2.2 on 2019-07-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0009_auto_20190714_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='memory_support',
            field=models.ManyToManyField(blank=True, to='cpudb.Memory'),
        ),
    ]
