# Generated by Django 2.2.2 on 2019-07-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0010_auto_20190714_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Brand'),
        ),
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Package'),
        ),
    ]
