# Generated by Django 2.2.2 on 2019-07-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpudb', '0011_auto_20190714_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpus',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cpudb.Package'),
        ),
    ]
