insert into cpudb_socket (name) values('AMD Socket 754'),('AMD Socket 939'),('AMD Socket 940'),('AMD Socket A'),('AMD Socket AM2'),('AMD Socket AM2+'),('AMD Socket AM3'),('AMD Socket AM3+'),('AMD Socket AM4'),('AMD Socket C32'),('AMD Socket F'),('AMD Socket FM1'),('AMD Socket FM2'),('AMD Socket FM2+'),('AMD Socket FP2'),('AMD Socket FP4'),('AMD Socket FP5'),('AMD Socket Fr2'),('AMD Socket FS1'),('AMD Socket FS1r2'),('AMD Socket FT1'),('AMD Socket FT3'),('AMD Socket FT4'),('AMD Socket G34'),('AMD Socket S1'),('AMD Socket SP1'),('AMD Socket SP3r2'),('AMD Socket TR4'),('Intel BGA 437'),('Intel BGA 441'),('Intel BGA 518'),('Intel BGA 559'),('Intel BGA 617'),('Intel BGA 676'),('Intel BGA 951'),('Intel BGA 956'),('Intel BGA1023'),('Intel BGA1090'),('Intel BGA1168'),('Intel BGA1170'),('Intel BGA1224'),('Intel BGA1234'),('Intel BGA1283'),('Intel BGA1288'),('Intel BGA1356'),('Intel BGA1364'),('Intel BGA1380'),('Intel BGA1440'),('Intel BGA1466'),('Intel BGA2270'),('Intel BGA5903'),('Intel Socket 1150'),('Intel Socket 1151'),('Intel Socket 1155'),('Intel Socket 1156'),('Intel Socket 1356'),('Intel Socket 1366'),('Intel Socket 1567'),('Intel Socket 2011'),('Intel Socket 2011-3'),('Intel Socket 2066'),('Intel Socket 3647'),('Intel Socket 370'),('Intel Socket 423'),('Intel Socket 478'),('Intel Socket 479'),('Intel Socket 604'),('Intel Socket 771'),('Intel Socket 775'),('Intel Socket G1'),('Intel Socket G2 (988B)'),('Intel Socket G3'),('Intel Socket M'),('Intel Socket P'),('PCIe x16'),('SFF 230-Pin');
insert into cpudb_process_size (name) values('10'),('12'),('130'),('14'),('180'),('22'),('28'),('32'),('40'),('45'),('65'),('7'),('90');

insert into cpudb_package (name) values (''),('BGA'),('BGA2'),('BGA769'),('FC-BGA1090'),('FC-BGA1168'),('FC-BGA1170'),('FC-BGA1234'),('FC-BGA12F'),('FC-BGA1356'),('FC-BGA1364'),('FC-BGA1380'),('FC-BGA1440'),('FC-BGA2270'),('FC-BGA5903'),('FC-BGA8'),('FC-LGA10'),('FC-LGA1150'),('FC-LGA1151'),('FC-LGA12C'),('FC-LGA14C'),('FC-LGA2066'),('FC-LGA3647'),('FC-LGA4'),('FC-LGA6'),('FC-LGA8'),('FC-PGA'),('FC-PGA12F'),('FC-PGA946'),('FCLGA-4094'),('PCIe x16'),('rPGA'),('SFF 230-Pin'),('µFCBGA8'),('µOPGA-1331'),('µPGA');

insert into cpudb_multiplier (name) values('10.0'),('10.5'),('11.0'),('11.5'),('12.0'),('12.5'),('13.0'),('13.2'),('13.5'),('14.0'),('14.4'),('14.5'),('15.0'),('15.5'),('16.0'),('16.5'),('17.0'),('17.5'),('18.0'),('18.5'),('19.0'),('19.5'),('20.0'),('21.0'),('22.0'),('23.0'),('23.5'),('24.0'),('25.0'),('26.0'),('27.0'),('28.0'),('29.0'),('30.0'),('31.0'),('32.0'),('33.0'),('34.0'),('35.0'),('36.0'),('37.0'),('38.0'),('39.0'),('40.0'),('41.0'),('42.0'),('43.0'),('5.0'),('6.0'),('6.5'),('7.0'),('7.5'),('8.0'),('8.5'),('9.0'),('9.5'),('unknown');


insert into cpudb_tdp (name) values('1'),('10'),('100'),('104'),('105'),('110'),('112'),('115'),('12'),('120'),('125'),('13'),('130'),('135'),('136'),('140'),('15'),('150'),('16'),('165'),('17'),('170'),('18'),('180'),('19'),('2'),('20'),('200'),('205'),('21'),('215'),('22'),('220'),('225'),('230'),('24'),('245'),('25'),('250'),('255'),('26'),('260'),('27'),('270'),('28'),('29'),('3'),('30'),('300'),('31'),('32'),('320'),('35'),('350'),('37'),('38'),('4'),('40'),('400'),('43'),('44'),('45'),('47'),('5'),('50'),('51'),('52'),('54'),('55'),('57'),('58'),('59'),('6'),('60'),('61'),('62'),('63'),('64'),('65'),('66'),('67'),('68'),('69'),('7'),('70'),('72'),('73'),('75'),('76'),('77'),('79'),('8'),('80'),('82'),('84'),('85'),('86'),('87'),('88'),('89'),('9'),('91'),('92'),('95'),('97');
insert into cpudb_market (name) values ('Desktop', 'Mobile', 'Server/Workstation');

insert into cpudb_productionstatus (name) values ('Active'), ('End-of-life'), ('unknown'), ('unreleased');

insert into cpudb_codename (name) values('Abu Dhabi'),('Agena'),('Albany'),('Allendale'),('Arrandale'),('Athens'),('Banias'),('Barcelona'),('Barton'),('Bay Trail-I'),('Bay Trail-M'),('Bay Trail-T'),('Bloomfield'),('Brisbane'),('Bristol Ridge'),('Broadwell'),('Broadwell-DT'),('Broadwell-E'),('Broadwell-U'),('Broadwell-Y'),('Callisto'),('Cascade Lake-AP'),('Cascade Lake-SP'),('Cedar Mill'),('Cedarview'),('Centerton'),('Clarkdale'),('Clawhammer'),('Clovertrail'),('Cloverview'),('Coffee Lake'),('Coffee Lake-H'),('Coffee Lake-S'),('Coffee Lake-U'),('Conroe'),('Conroe XE'),('Conroe-CL'),('Conroe-L'),('Coppermine'),('Coppermine T'),('Cranford'),('Crystalwell'),('Delhi'),('Dempsey'),('Deneb'),('Denmark'),('Desna'),('Diamondville'),('Dothan'),('Egypt'),('Gainestown'),('Gallatin'),('Gladden'),('Griffin'),('Gulftown'),('Haswell'),('Haswell-E'),('Haswell-EX'),('Haswell-ULT'),('Haswell-WS'),('Heka'),('Hondo'),('Interlagos'),('Irwindale'),('Italy'),('Ivy Bridge'),('Ivy Bridge-E'),('Ivy Bridge-EN'),('Ivy Bridge-EP'),('Jasper Forest'),('Kabini'),('Kaby Lake'),('Kaby Lake G'),('Kaby Lake-DT'),('Kaby Lake-H'),('Kaby Lake-R'),('Kaby Lake-X'),('Kaveri'),('Kentsfield'),('Knights Corner'),('Knights Ferry'),('Knights Landing'),('Knights Mill'),('Kuma'),('Kyoto'),('Lancaster'),('Lima'),('Lincroft'),('Llano'),('Lynnfield'),('Magny-Cours'),('Manchester'),('Manila'),('Merom'),('Merom XE'),('Merom-L'),('NewCastle'),('Nocona'),('Northwood'),('Ontario'),('Orleans'),('Palomino'),('Paxville'),('Penryn'),('Penryn QC'),('Penryn QC XE'),('Penryn XE'),('Penryn-L'),('Penwell'),('Picasso'),('Pineview'),('Potomac'),('Prescott'),('Presler'),('Prestonia'),('Propus'),('Rana'),('Raven Ridge'),('Raven Ridge 2'),('Regor'),('Richland'),('San Diego'),('Sandy Bridge'),('Sandy Bridge-E'),('Sandy Bridge-EN'),('Sandy Bridge-EP'),('Sargas'),('Seattle'),('Seoul'),('Silverthorne'),('Skylake'),('Skylake-H'),('Skylake-S'),('Skylake-SP'),('Skylake-W'),('Skylake-X'),('SledgeHammer'),('Smithfield'),('Sodaville'),('Sparta'),('Stealey'),('Stellarton'),('Steppe Eagle'),('Stoney Ridge'),('Temash'),('Thoroughbred'),('Thorton'),('Thuban'),('Thunderbird'),('Thunderbird B'),('Thunderbird C'),('Toledo'),('Toliman'),('Trinity'),('Troy'),('Tualatin'),('Tulsa'),('Tunnel Creek'),('Venice'),('Venus'),('Vishera'),('Westmere-EP'),('Westmere-EX'),('Whiskey Lake-U'),('Willamette'),('Windsor'),('Wolfdale'),('Woodcrest'),('Yonah'),('Yorkfield'),('Zacate'),('Zambezi'),('Zen'),('Zen 2'),('Zosma');

insert into cpudb_generation (name) values 
('A10 (Bristol Ridge)'),
('A10 (Kaveri)'),
('A10 (Richland)'),
('A10 (Trinity)'),
('A12 (Bristol Ridge)'),
('A4 (Kabini)'),
('A4 (Llano)'),
('A4 (Richland)'),
('A4 (Stoney Ridge)'),
('A4 (Temash)'),
('A4 (Trinity)'),
('A6 (Bristol Ridge)'),
('A6 (Kabini)'),
('A6 (Llano)'),
('A6 (Richland)'),
('A6 (Stoney Ridge)'),
('A6 (Temash)'),
('A6 (Trinity)'),
('A8 (Bristol Ridge)'),
('A8 (Kaveri)'),
('A8 (Llano)'),
('A8 (Richland)'),
('A8 (Trinity)'),
('A9 (Stoney Ridge)'),
('Athlon (Bristol Ridge)'),
('Athlon (Zen (Raven Ridge 2))'),
('Athlon (Zen)'),
('Athlon 64 (Clawhammer)'),
('Athlon 64 (Lima)'),
('Athlon 64 (NewCastle)'),
('Athlon 64 (Orleans)'),
('Athlon 64 (SledgeHammer)'),
('Athlon 64 (Venice)'),
('Athlon 64 FX (Clawhammer)'),
('Athlon 64 FX (San Diego)'),
('Athlon 64 FX (Toledo)'),
('Athlon 64 FX (Windsor)'),
('Athlon 64 X2 (Brisbane)'),
('Athlon 64 X2 (Manchester)'),
('Athlon 64 X2 (Windsor)'),
('Athlon II X2 (Regor)'),
('Athlon II X3 (Rana)'),
('Athlon II X4 (Llano)'),
('Athlon II X4 (Propus)'),
('Athlon Model 4 (Thunderbird B)'),
('Athlon Model 4 (Thunderbird C)'),
('Athlon Model 4 (Thunderbird)'),
('Athlon X2 (Griffin)'),
('Athlon X2 (Kuma)'),
('Athlon XP (Barton)'),
('Athlon XP (Palomino)'),
('Athlon XP (Thoroughbred-B)'),
('Athlon XP (Thorton)'),
('Atom (Bay Trail)'),
('Atom (Cedarview)'),
('Atom (Centerton)'),
('Atom (Clovertrail)'),
('Atom (Cloverview)'),
('Atom (Diamondville)'),
('Atom (Lincroft)'),
('Atom (Penwell)'),
('Atom (Pineview)'),
('Atom (Silverthorne)'),
('Atom (Sodaville)'),
('Atom (Stealey)'),
('Atom (Stellarton)'),
('Atom (Tunnel Creek)'),
('C (Ontario)'),
('Celeron (Allendale)'),
('Celeron (Bay Trail)'),
('Celeron (Broadwell-U)'),
('Celeron (Clarkdale)'),
('Celeron (Coffee Lake)'),
('Celeron (Conroe)'),
('Celeron (Haswell)'),
('Celeron (Ivy Bridge)'),
('Celeron (Jasper Forest)'),
('Celeron (Kaby Lake)'),
('Celeron (Northwood)'),
('Celeron (Sandy Bridge)'),
('Celeron (Skylake)'),
('Celeron (Wolfdale)'),
('Celeron D (Cedar Mill)'),
('Celeron D (Prescott)'),
('Core 2 Duo (Allendale)'),
('Core 2 Duo (Conroe)'),
('Core 2 Duo (Merom)'),
('Core 2 Duo (Wolfdale)'),
('Core 2 Extreme (Conroe XE)'),
('Core 2 Extreme (Kentsfield XE)'),
('Core 2 Extreme (Merom XE)'),
('Core 2 Extreme (Penryn QC XE)'),
('Core 2 Extreme (Penryn XE)'),
('Core 2 Extreme (Yorkfield XE)'),
('Core 2 Quad (Kentsfield)'),
('Core 2 Quad (Penryn QC)'),
('Core 2 Quad (Yorkfield)'),
('Core 2 Solo (Merom)'),
('Core 2 Solo (Penryn)'),
('Core Duo (Yonah)'),
('Core i3 (Arrandale)'),
('Core i3 (Broadwell-U)'),
('Core i3 (Clarkdale)'),
('Core i3 (Coffee Lake Refresh)'),
('Core i3 (Coffee Lake)'),
('Core i3 (Haswell)'),
('Core i3 (Ivy Bridge)'),
('Core i3 (Kaby Lake-U Refresh)'),
('Core i3 (Kaby Lake)'),
('Core i3 (Sandy Bridge)'),
('Core i3 (Skylake)'),
('Core i5 (Arrandale)'),
('Core i5 (Broadwell-U)'),
('Core i5 (Broadwell)'),
('Core i5 (Clarkdale)'),
('Core i5 (Coffee Lake Refresh)'),
('Core i5 (Coffee Lake-H)'),
('Core i5 (Coffee Lake)'),
('Core i5 (Haswell)'),
('Core i5 (Ivy Bridge)'),
('Core i5 (Kaby Lake-G)'),
('Core i5 (Kaby Lake-U Refresh)'),
('Core i5 (Kaby Lake)'),
('Core i5 (Lynnfield)'),
('Core i5 (Sandy Bridge)'),
('Core i5 (Skylake-H)'),
('Core i5 (Skylake)'),
('Core i5 (X-Series)'),
('Core i7 (Arrandale)'),
('Core i7 (Bloomfield EE)'),
('Core i7 (Bloomfield)'),
('Core i7 (Broadwell-E)'),
('Core i7 (Broadwell-U)'),
('Core i7 (Broadwell)'),
('Core i7 (Coffee Lake Refresh)'),
('Core i7 (Coffee Lake-H)'),
('Core i7 (Coffee Lake)'),
('Core i7 (Crystalwell)'),
('Core i7 (Gulftown EE)'),
('Core i7 (Gulftown)'),
('Core i7 (Haswell EE)'),
('Core i7 (Haswell-E EE)'),
('Core i7 (Haswell)'),
('Core i7 (Ivy Bridge EE)'),
('Core i7 (Ivy Bridge-E EE)'),
('Core i7 (Ivy Bridge-E)'),
('Core i7 (Ivy Bridge)'),
('Core i7 (Kaby Lake-G)'),
('Core i7 (Kaby Lake-H)'),
('Core i7 (Kaby Lake-U Refresh)'),
('Core i7 (Kaby Lake)'),
('Core i7 (Lynnfield)'),
('Core i7 (Sandy Bridge EE)'),
('Core i7 (Sandy Bridge-E EE)'),
('Core i7 (Sandy Bridge-E)'),
('Core i7 (Sandy Bridge)'),
('Core i7 (Skylake)'),
('Core i7 (X-Series 9th Gen)'),
('Core i7 (X-Series)'),
('Core i7 40th (Coffee Lake)'),
('Core i9 (Coffee Lake Refresh)'),
('Core i9 (Coffee Lake-H)'),
('Core i9 (X-Series 9th Gen)'),
('Core i9 (X-Series)'),
('Core i9 Extreme (X-Series 9th Gen)'),
('Core i9 Extreme (X-Series)'),
('Core M (Broadwell-Y)'),
('Core m3 (Cannon Lake-Y)'),
('Core Solo (Yonah)'),
('E (Zacate)'),
('E1 (Kabini)'),
('E1 (Zacate 2)'),
('E2 (Kabini)'),
('E2 (Llano)'),
('E2 (Zacate 2)'),
('EPYC (Zen)'),
('EPYC Embedded (Snowy Owl)'),
('FX (Vishera)'),
('FX (Zambezi)'),
('Mobile Athlon 64 (Clawhammer)'),
('Mobile Pentium 4 (Northwood)'),
('Mobile Pentium 4 HT (Northwood)'),
('Mobile Pentium 4 HT (Prescott)'),
('Mobile Sempron (Albany)'),
('Opteron (Abu Dhabi)'),
('Opteron (Athens (D4))'),
('Opteron (Athens (E4))'),
('Opteron (Barcelona)'),
('Opteron (Delhi)'),
('Opteron (Interlagos)'),
('Opteron (Magny-Cours)'),
('Opteron (Seattle)'),
('Opteron (Seoul)'),
('Opteron (SledgeHammer (B3))'),
('Opteron (SledgeHammer (C0))'),
('Opteron (SledgeHammer (CG))'),
('Opteron (Troy (D4))'),
('Opteron (Troy (E4))'),
('Opteron (Venus (E4))'),
('Opteron (X-Series)'),
('Opteron X2 (Denmark)'),
('Opteron X2 (Egypt)'),
('Opteron X2 (Italy)'),
('Pentium (Arrandale)'),
('Pentium (Broadwell-U)'),
('Pentium (Clarkdale)'),
('Pentium (Haswell)'),
('Pentium (Ivy Bridge)'),
('Pentium (Kaby Lake)'),
('Pentium (Sandy Bridge)'),
('Pentium (Skylake)'),
('Pentium 4 (Northwood)'),
('Pentium 4 (Prescott)'),
('Pentium 4 (Willamette)'),
('Pentium 4 HT (Cedar Mill)'),
('Pentium 4 HT (Gallatin EE)'),
('Pentium 4 HT (Northwood)'),
('Pentium 4 HT (Prescott EE)'),
('Pentium 4 HT (Prescott)'),
('Pentium 4-M (Northwood)'),
('Pentium D (Presler EE)'),
('Pentium D (Presler)'),
('Pentium D (Smithfield EE)'),
('Pentium D (Smithfield)'),
('Pentium Dual-Core (Allendale)'),
('Pentium Dual-Core (Penryn)'),
('Pentium Dual-Core (Wolfdale)'),
('Pentium Gold (Coffee Lake)'),
('Pentium III (Coppermine T)'),
('Pentium III (Coppermine)'),
('Pentium III (Tualatin)'),
('Pentium M (Banias)'),
('Pentium M (Dothan)'),
('Pentium Silver (Coffee Lake)'),
('Phenom II X2 (Callisto)'),
('Phenom II X3 (Heka)'),
('Phenom II X4 (Deneb)'),
('Phenom II X4 (Propus)'),
('Phenom II X4 (Zosma)'),
('Phenom II X6 (Thuban)'),
('Phenom X3 (Toliman)'),
('Phenom X4 (Agena)'),
('Ryzen 3 (Zen (Raven Ridge))'),
('Ryzen 3 (Zen)'),
('Ryzen 3 (Zen+ (Picasso))'),
('Ryzen 3 (Zen+ (Pinnacle Ridge))'),
('Ryzen 5 (Zen (Raven Ridge))'),
('Ryzen 5 (Zen 2)'),
('Ryzen 5 (Zen)'),
('Ryzen 5 (Zen+ (Picasso))'),
('Ryzen 5 (Zen+ (Pinnacle Ridge))'),
('Ryzen 7 (Zen (Raven Ridge))'),
('Ryzen 7 (Zen 2)'),
('Ryzen 7 (Zen)'),
('Ryzen 7 (Zen+ (Picasso))'),
('Ryzen 7 (Zen+ (Pinnacle Ridge))'),
('Ryzen 9 (Zen 2)'),
('Ryzen Embedded (Great Horned Owl)'),
('Ryzen Threadripper (Zen)'),
('Ryzen Threadripper (Zen+)'),
('Sempron (Barton)'),
('Sempron (Manilla)'),
('Sempron (Regor)'),
('Sempron (Sargas)'),
('Sempron (Sparta)'),
('Sempron X2 (Brisbane)'),
('Turion 64 (Lancaster)'),
('Turion X2 (Griffin)'),
('Turion X2 Ultra (Griffin)'),
('Xeon (Bloomfield)'),
('Xeon (Dempsey)'),
('Xeon (Gainestown)'),
('Xeon (Gallatin)'),
('Xeon (Gulftown)'),
('Xeon (Irwindale)'),
('Xeon (Nocona)'),
('Xeon (Paxville DP)'),
('Xeon (Prestonia)'),
('Xeon (Tulsa)'),
('Xeon (Westmere-EP)'),
('Xeon (Woodcrest)'),
('Xeon Bronze (Skylake-SP)'),
('Xeon E (Coffee Lake)'),
('Xeon E3 (Broadwell-DT)'),
('Xeon E3 (Gladden)'),
('Xeon E3 (Haswell-WS)'),
('Xeon E3 (Ivy Bridge)'),
('Xeon E3 (Kaby Lake-DT)'),
('Xeon E3 (Sandy Bridge)'),
('Xeon E3 (Skylake-S)'),
('Xeon E5 (Ivy Bridge-E)'),
('Xeon E5 (Ivy Bridge-EN)'),
('Xeon E5 (Ivy Bridge-EP)'),
('Xeon E5 (Sandy Bridge-E)'),
('Xeon E5 (Sandy Bridge-EN)'),
('Xeon E5 (Sandy Bridge-EP)'),
('Xeon E7 (Haswell-EX)'),
('Xeon E7 (Westmere-EX)'),
('Xeon Gold (Skylake-SP)'),
('Xeon MP (Cranford)'),
('Xeon MP (Paxville MP)'),
('Xeon MP (Potomac)'),
('Xeon Phi (Knights Corner)'),
('Xeon Phi (Knights Ferry)'),
('Xeon Phi (Knights Landing)'),
('Xeon Phi (Knights Mill)'),
('Xeon Platinum (Cascade Lake-AP)'),
('Xeon Platinum (Cascade Lake-SP)'),
('Xeon Platinum (Skylake-SP)'),
('Xeon Silver (Skylake-SP)'),
('Xeon W (Skylake-W)'),
('Z (Desna)'),
('Z (Hondo)');

insert into cpudb_memorysupport (name) values
('DDR1'),
('DDR1, DDR2'),
('DDR1, DDR2, DDR3'),
('DDR2'),
('DDR2, DDR3'),
('DDR3'),
('DDR3, DDR4'),
('DDR4'),
('unknown');

insert into cpudb_core (name) values
('1'),
('10'),
('12'),
('14'),
('16'),
('18'),
('2'),
('24'),
('26'),
('28'),
('3'),
('32'),
('4'),
('48'),
('56'),
('57'),
('6'),
('60'),
('61'),
('64'),
('68'),
('72'),
('8');


insert into cpudb_thread (name) values 
('1'),
('112'),
('12'),
('128'),
('16'),
('2'),
('20'),
('228'),
('24'),
('240'),
('244'),
('256'),
('272'),
('28'),
('288'),
('3'),
('32'),
('36'),
('4'),
('48'),
('52'),
('56'),
('6'),
('64'),
('8'),
('96');


insert into cpudb_integraated_graphics (name) values
('GMA'),
('GMA 3150'),
('GMA 500'),
('GMA 600'),
('HD 630'),
('HD 8400'),
('HD Graphics'),
('HD Graphics 530'),
('HD Graphics P630'),
('Intel HD'),
('Intel HD (Haswell)'),
('Intel HD (Sandy Bridge)'),
('Intel HD 2000'),
('Intel HD 2500'),
('Intel HD 3000'),
('Intel HD 4000'),
('Intel HD 4200'),
('Intel HD 4400'),
('Intel HD 4600'),
('Intel HD 5000'),
('Intel HD 510'),
('Intel HD 5100'),
('Intel HD 5200'),
('Intel HD 530'),
('Intel HD 5300'),
('Intel HD 5500'),
('Intel HD 6000'),
('Intel HD 610'),
('Intel HD 630'),
('Intel HD Graphics 630'),
('Intel HD P3000'),
('Intel HD P4000'),
('Intel HD P4600'),
('Intel Iris 6100'),
('Intel Iris Pro 580'),
('Intel Iris Pro P6300'),
('Intel Iris? Pro 5200'),
('Iris Pro Graphics 6200'),
('Iris Pro Plus'),
('N/A'),
('Radeon HD 6250'),
('Radeon HD 6290'),
('Radeon HD 6310'),
('Radeon HD 6320'),
('Radeon HD 6370D'),
('Radeon HD 6380G'),
('Radeon HD 6410D'),
('Radeon HD 6480G'),
('Radeon HD 6520G'),
('Radeon HD 6530D'),
('Radeon HD 6550D'),
('Radeon HD 6620G'),
('Radeon HD 7310'),
('Radeon HD 7340'),
('Radeon HD 7400G'),
('Radeon HD 7420G'),
('Radeon HD 7480D'),
('Radeon HD 7500G'),
('Radeon HD 7520G'),
('Radeon HD 7540D'),
('Radeon HD 7560D'),
('Radeon HD 7600G'),
('Radeon HD 7620G'),
('Radeon HD 7640G'),
('Radeon HD 7660D'),
('Radeon HD 7660G'),
('Radeon HD 8180'),
('Radeon HD 8210'),
('Radeon HD 8240'),
('Radeon HD 8250'),
('Radeon HD 8280'),
('Radeon HD 8310G'),
('Radeon HD 8330'),
('Radeon HD 8350G'),
('Radeon HD 8370D'),
('Radeon HD 8400'),
('Radeon HD 8410G'),
('Radeon HD 8450G'),
('Radeon HD 8470D'),
('Radeon HD 8510G'),
('Radeon HD 8550G'),
('Radeon HD 8570D'),
('Radeon HD 8610G'),
('Radeon HD 8650D'),
('Radeon HD 8650G'),
('Radeon HD 8670D'),
('Radeon R4'),
('Radeon R5'),
('Radeon R5E'),
('Radeon R7'),
('Radeon RX Vega 10'),
('Radeon RX Vega 11'),
('Radeon RX Vega M GH'),
('Radeon RX Vega M GL'),
('Radeon Vega 3'),
('Radeon Vega 6'),
('Radeon Vega 8'),
('SGX 544MP2'),
('UHD 620'),
('UHD 630'),
('UHD Graphics 605'),
('UHD Graphics 610'),
('UHD Graphics 630');  
